// layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";

// Carregando as fontes locais com o `next/font/local`
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",  // Caminho para a fonte
  variable: "--font-geist-sans", // Variável CSS para usar em todo o projeto
  weight: "100 900",  // Faixa de peso da fonte
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",  // Caminho para a fonte
  variable: "--font-geist-mono", // Variável CSS para usar em todo o projeto
  weight: "100 900",  // Faixa de peso da fonte
});

// Metadados globais da aplicação
export const metadata: Metadata = {
  title: "Create Next App",  // Título da página
  description: "Generated by create next app",  // Descrição da página
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* Envolvendo a aplicação com o AuthProvider */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
